baseURL = "/"
languageCode = "en-us"
theme = "hugo-winston-theme"
themesDir = "themes"
title = "Hugo Winston Theme"
paginate = 3
pygmentsCodeFences = true
pygmentsCodefencesGuessSyntax = true
pygmentsUseClasses = true

[module]
  [module.hugoVersion]
    extended = true
    min = "0.55.0"

[params]
  google_analytics_id = ""
  twitter_handle = "@zerostaticio"
  showAuthorOnHomepage = true
  showAuthorOnPosts = false
  showPostsOnHomepage = false
  addDot = true
  addFrame = true
  highlightColor = '#7b16ff'

# markdown config settings https://gohugo.io/getting-started/configuration-markup/#goldmark
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = false
      unsafe = true
      xhtml = false

[menu]
  [[menu.main]]
    identifier = 'home'
    name = 'Home'
    url = '/'
    weight = 1
